In [1]:
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OrdinalEncoder
from sklearn.naive_bayes import CategoricalNB
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import OrdinalEncoder
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import f1_score
df =pd.read_csv("ebay_iphone.csv")
df.drop(columns="Name",inplace=True)
for col in df:
    print(df[col].value_counts())

Seller
  firma       535
  prywatny    405
Name: count, dtype: int64
Condition
Używany             642
Tylko na części     120
Fabrycznie nowy      65
Odnowiony            60
Nowy (inny)          53
Name: count, dtype: int64
Price
906.199394    16
795.140000    10
759.140000    10
699.250000     9
395.570000     8
              ..
157.170000     1
259.720000     1
149.680000     1
153.680000     1
149.930000     1
Name: count, Length: 595, dtype: int64
Shipping Cost
0.00      47
64.51     24
86.02     15
62.32     14
85.98     13
          ..
96.26      1
86.23      1
134.06     1
141.01     1
73.02      1
Name: count, Length: 531, dtype: int64
Shipping Country
 Stany Zjednoczone    499
 Wielka Brytania      150
 Niemcy               141
 Włochy                66
 Chiny                 26
 Polska                13
 Francja                9
 Kanada                 8
 Austria                5
 Litwa                  5
 Japonia                4
 Szwajcaria             4
 Irlandia               3
 Hongkong               3
 Belgia                 2
 Australia              2
Name: count, dtype: int64
Free Return
False    883
True      57
Name: count, dtype: int64
Last Item
False    907
True      33
Name: count, dtype: int64
Best Seller
False    739
True     201
Name: count, dtype: int64
Buy Now
False    907
True      33
Name: count, dtype: int64
Generation
12          180
11          155
se           77
13           76
xr           56
7            43
xs           42
15           41
6s           40
5            36
6            33
8            33
14           23
4            16
4s           16
x            14
5s           13
1            10
5c            7
3gs           5
3g            4
ze            2
specimen      2
Name: count, dtype: int64

## Tworzenie kategorii USA

In [2]:
df["Shipping Country"] = df["Shipping Country"].apply(lambda x : x.strip())
df["USA"] = df["Shipping Country"].apply(lambda x : 1 if str(x) =="Stany Zjednoczone" else 0)
df.drop(columns="Shipping Country",inplace=True)
df

,Seller,Condition,Price,Shipping Cost,Free Return,Last Item,Best Seller,Buy Now,Generation,USA
0,prywatny,Używany,576.33,62.32,False,False,False,False,13,0
1,prywatny,Używany,950.00,0.00,False,False,False,False,12,0
2,firma,Używany,4.95,74.01,False,False,False,False,12,0
3,firma,Tylko na części,19.35,64.30,False,False,False,False,12,0
4,prywatny,Tylko na części,200.00,0.00,False,False,False,False,11,0
...,...,...,...,...,...,...,...,...,...,...
935,prywatny,Używany,49.43,75.96,False,False,False,False,4,0
936,firma,Używany,898.83,107.80,False,False,True,False,12,1
937,prywatny,Tylko na części,199.90,164.87,False,False,False,False,8,0
938,prywatny,Używany,149.93,73.02,False,False,False,False,5,0
939,firma,Odnowiony,817.14,38.67,True,True,True,True,7,0

## Transformacja wartości Generation na osobne kolumny w zalężności od wartości

In [3]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse_output=False)
one_hot_encoded = enc.fit_transform(df[["Generation"]])

one_hot_df = pd.DataFrame(one_hot_encoded, columns=enc.get_feature_names_out(["Generation"]))

df = df.merge(one_hot_df,left_index=True, right_index=True)
df.drop(columns="Generation",inplace=True)
df

,Seller,Condition,Price,Shipping Cost,Free Return,Last Item,Best Seller,Buy Now,USA,Generation_1,...,Generation_6s,Generation_7,Generation_8,Generation_se,Generation_specimen,Generation_x,Generation_xr,Generation_xs,Generation_ze,Generation_nan
0,prywatny,Używany,576.33,62.32,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,prywatny,Używany,950.00,0.00,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,firma,Używany,4.95,74.01,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,firma,Tylko na części,19.35,64.30,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,prywatny,Tylko na części,200.00,0.00,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,prywatny,Używany,49.43,75.96,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
936,firma,Używany,898.83,107.80,False,False,True,False,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
937,prywatny,Tylko na części,199.90,164.87,False,False,False,False,0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
938,prywatny,Używany,149.93,73.02,False,False,False,False,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
939,firma,Odnowiony,817.14,38.67,True,True,True,True,0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
df.drop(columns="Generation",inplace=True)

KeyError: "['Generation'] not found in axis"

## Sprawdzenie korelacji i zakodowanie zmiennych kategorycznych

In [ ]:
col_list_enc=df.columns.tolist()
#col_list_enc.remove("Condition")
col_list_enc_corr = col_list_enc.copy()
col_list_enc.remove("Price")
col_list_enc.remove("Shipping Cost")

enc = OrdinalEncoder()
df[col_list_enc]=enc.fit_transform(df[col_list_enc])
fig, ax = plt.subplots(figsize=(12,12))
sns.heatmap(df[col_list_enc_corr].corr(), annot=True, center=0.0,ax=ax,vmax=1,vmin=-1)

## Usuwanie wysoko skorelowanych atrybutów

In [ ]:
df.drop(columns="Buy Now",inplace=True)

## Podział danych na treningowe, testowe i walidacyjne

In [ ]:
X = df.drop(columns="Condition")
y = df["Condition"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 5)
X_train,X_valid,y_train,y_valid = train_test_split(X_train,y_train,test_size=0.2,random_state=5)

## Tworzenie modeli

### Regresja logistyczna

In [ ]:
lr= LogisticRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_valid)
print(classification_report(y_pred,y_valid))

### KNN

In [ ]:
from sklearn.preprocessing import StandardScaler
X_train_s = StandardScaler().fit_transform(X_train)
X_valid_s = StandardScaler().fit_transform(X_valid)
knn  = KNeighborsClassifier()
knn.fit(X_train_s,y_train)
y_pred = knn.predict(X_valid_s)
print(classification_report(y_pred,y_valid))

### Drzewo decyzyjne

In [ ]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
y_pred = dt.predict(X_valid)
print(classification_report(y_pred,y_valid))

### Las losoway

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_valid)
print(classification_report(y_pred,y_valid)) # 38,6

### Dokładność jest najlepsza dla lasu losowego

In [ ]:
y_pred = rf.predict(X_test)
print(classification_report(y_pred,y_test))

In [ ]:
import joblib 
joblib.dump(lr, 'condition_classifier.pkl')